import { ShopItem } from './types';

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'deep_space_skin',
    name: 'Deep Space Skin',
    description: 'Stealth coating designed for the vacuum of hard space.',
    category: 'ship',
    price: 50,
    priceType: 'crystals',
    icon: 'rocket_launch',
    detailText: 'STEALTH COATING LVL 1',
    imageAlt: 'Concept art of a deep space starship hull with matte black carbon textures and glowing red sensor panels.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAaPHfrT4lbXD74Pbt451Jy0TvwD79TfNcuXZjL8aobNhxAJqtC3emHZ5H48klfrox8ve3eYgQN6vSArgU0N2CYsyFr5bxBq1_hR3agR9nz7EcGDyKDcxz51oIOzj_iA8EA5vd73AumJPtSJuptdoLWnr5NLQ25mBNDupbO4HjrW4WLeCgScWppqz7BG3dFUA0jHnSKAK5-DZuoniPN7ibxOBOi7TQb15lyig8RHzY0BKQxf3RA103gDru_MNVL999rxaLvRCN0mQw',
  },
  {
    id: 'quantum_warp_drive',
    name: 'Quantum Warp Drive',
    description: 'Harness zero-point energy to unlock warp velocity.',
    category: 'ship',
    price: 75,
    priceType: 'crystals',
    icon: 'dynamic_form',
    detailText: 'ENGINE OVERCLOCK MOD',
    imageAlt: 'A sophisticated quantum warp drive core glowing with intense cerulean light particles.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDHWYASnYrYeGP0t1Nxn5UqLgV1H0OTyJkBYbs9GDKQjrXuIRx53RduOb2nF8DlioscDVRPXleIvpNlfdFOWFocI8qBJIRy336QvkaOHCpIf7tmOJxbzo2BLOdFuHtojEptFTdqj0trb1FtnU1KCeg3HxZT9QC-te8af8tXtj238d2Z6E1njefhgp_4kV6pITNs_cnGTy0jtJbkr4aVI_SfWHc-N1hDzp2-eO16nrTWEG6A7mqhntF8_ChQZ8Vj8CO7fNEHhEStWvY',
  },
  {
    id: 'atmospheric_shielding',
    name: 'Atmospheric Shielding',
    description: 'Reinforced ion shields to protect against cosmic debris.',
    category: 'ship',
    price: 100,
    priceType: 'crystals',
    icon: 'shield',
    detailText: 'REINFORCED ION LAYER',
    imageAlt: 'A shimmering translucent energy shield refracting stellar light in deep space.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5WdFZtpnDP59z9IKRYrRgD-9syau8TDyZhtSgwEOrhLXPzhEWdA3rhNf55crwSxPNzsZ8mOeGootkttW_DQAC5NIPrAeHykiFzZ8NvEKmXOWGkk4H5IsHhvuz-I5-jpPaSi8H4x-Z4X4_i6prpC0ciWJMgy4pp8w_GUQUR8RwWLxzrzT_rlI4YbFaowopyudjquH9rmWfPk56ZD7nQmjHpUKoMx2yrNlnsQ3Xyo_Cubplbx1AmiapvdWa6hmA3jik79D00Tjeg2I',
  },
  {
    id: 'retro_apollo_helmet',
    name: 'Retro Apollo Helmet',
    description: 'A vintage pressurized glass dome with gold-leaf accents.',
    category: 'avatar',
    price: 40,
    priceType: 'crystals',
    icon: 'architecture',
    detailText: 'VINTAGE PRESSURIZED CLASS DOME',
    imageAlt: 'Retro Apollo Helmet icon depicting a classic retro-futuristic space helmet design.',
    imageUrl: '',
  },
  {
    id: 'nebula_cape',
    name: 'Nebula Cape',
    description: 'Flowing particles of cosmic dust that trail behind you.',
    category: 'avatar',
    price: 80,
    priceType: 'crystals',
    icon: 'clear_all',
    detailText: 'FLOWING PARTICLES OF COSMIC DUST',
    imageAlt: 'Nebula Cape icon displaying glowing particle tails in space.',
    imageUrl: '',
  },
  {
    id: 'cosmic_radio',
    name: 'Cosmic Radio Station',
    description: 'Unlock exclusive lo-fi space beats for your focus sessions.',
    category: 'community',
    price: 0,
    priceType: 'free',
    icon: 'radio',
    detailText: 'EXCLUSIVE SPACE LO-FI CHANNEL',
    imageAlt: 'Retro space radio emitting rhythmic lofi soundwaves.',
    imageUrl: '',
  },
  {
    id: 'vanguard_fleet_emblem',
    name: 'Vanguard Fleet Emblem',
    description: 'Show your veteran status in global habit leaderboards.',
    category: 'community',
    price: 30,
    priceType: 'crystals',
    icon: 'military_tech',
    detailText: 'EXCLUSIVE VETERAN LEADERBOARD ACCESS',
    imageAlt: 'Vanguard Fleet Emblem representing veteran rank.',
    imageUrl: '',
  },
];
